### ISSUE TITLE
how can I do request to the private services?

### ISSUE THREAD

**Issue by archraziel** [shashimal/terraform-ecs#3]
Could you please explain how can I from my local do requests to the microservices running inside the private ALB?

For example:
I want to run the frontend on my local machine but call the micro-services that are running in the aws environment

**Comment by shashimal** [comment]
Hi @archraziel,

The purpose of private ALB is to communicate between services within the VPC. If you want to expose your private services to the outside, the best option is, expose them via an Internet-facing (public) ALB.  So your frontend can call the public load balancer and then it forwards the traffic to private services.

**Comment by archraziel** [comment]
Hey @shashimal 

I gave you the wrong idea.
What I want is to have private microservices but that the developers can call it when they need during the development phase.

But I was able to do it. I created an EC2 instance and I just need to ssh into it to port forward the microservices in AWS to localhost.

Thank you for you amazing repo!
